### ISSUE TITLE
As a user, I want to manage transaction for booked project. 

### ISSUE THREAD

**Issue by nasaku898** [kevin-ghannoum/soen490#160]
![image.png](https://images.zenhubusercontent.com/6009a0a0e8f11a200bd5a9d4/654dcaa6-0121-4cb0-b185-dde34b548822)

for this feature to be consider complete:
- meet the requirement
- diagrams associated to it
- unit tests
- e2e tests
- acceptance test
- proper mockup

**Comment by Mnx458** [comment]
done
