### ISSUE TITLE
Complete UI mockups for expenses and productions page

### ISSUE THREAD

**Issue by jmezaber** [kevin-ghannoum/soen490#182]
Epic/User story #160

**Comment by huangs08** [comment]
This ticket will be updated to a lower priority. We will keep our focus on the newer/higher priority tickets.

**Comment by jmezaber** [comment]
![image.png](https://images.zenhubusercontent.com/61c78e5fefa962288075e7ec/40c53228-5845-448e-9c11-fb008c6017a9)
