### ISSUE TITLE
As a user, I want to schedule a meeting

### ISSUE THREAD

**Issue by nasaku898** [kevin-ghannoum/soen490#200]
- Be able to create a meeting
create the meeting in db
invite people to the meeting (they are able to accept, refuse, tentatively accept)
add/edit description of the meeting
delete meeting
Add date and time
Location (room number, zoom link, etc.)
Inspiration:
![image.png](https://images.zenhubusercontent.com/6009a0a0e8f11a200bd5a9d4/7982dacd-2528-4814-8a1b-7350b12dd129)

- Display the user's meeting on a calendar. Similar to outlook or google calendar. We can maybe use this library or other.
https://jquense.github.io/react-big-calendar/examples/index.html

Might have to investigate our database design on events. Make sure it has all the field we need. We can update if needed. 

- Send email to recipient with a description of the meeting and a link to our application to accept/refuse the meeting. (must be login)

For this story to be complete you must:

- Have the functionality listed above
- UI mockup
- Test backend/frontend
- Diagram (rest diagram/class diagram) (if needed)
- Any additional documention (if present)

**Comment by Manraj45** [comment]
As discussed in the meeting:
Attributes:
title
date
start
end
location (text field)
description

invitee (try to implement auto-complete)

POST


1- Create event in db
    make sure to properly link the table to user and invitee
2- Send email to invitee

GET ALL
Query based on user event. Get all event he created and all events he was invited. 
Return event model as a new DTO. 
Have the same attribute but all a list for "invitee":[{name:simon, email: simonlim898@mail.com},... {}] and a attribute called Owner: {name:simon, email: simonlim898@m,,} (email)
include id also

PUT 
Edit all attributes
all attribute will be sent and id too
Make sure to make the check that the one editting is the owner
send email to invitee for an update

Delete
remove the meeting and send email to notice cancellation. 


To accept have a url like this in the email

Create endpoint to accept a confirmation
url.com/email/accept?user=simon@s.com&accept=true&id=asdasdas
