### ISSUE TITLE
[Acceptance test] As a business user, I want to create a client account

### ISSUE THREAD

**Issue by nasaku898** [kevin-ghannoum/soen490#72]
- Be able to create a new client account (Name, business name, industry, address, phone, email, website, social
- media pages, username, password, status)

**Comment by SamuelChuang98** [comment]
Just in case it wasn't clear, business name, industry, website, and social media page are optional inputs when adding a new client. The rest are mandatory. The address should be split into street address, city, and postal code for future functionalities

**Comment by SamuelChuang98** [comment]
My bad haha, a client is assumed to be your average consumer. So not everyone has a business
